AerolineaV1/Controllers/AvionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AerolineaV1.Models;

namespace AerolineaV1.Controllers
{
    public class AvionController : Controller
    {
        private readonly AvionContext _context;

        public AvionController(AvionContext context)
        {
            _context = context;
        }

        // GET: Avion
        public async Task<IActionResult> Index()
        {
            return View(await _context.Aviones.ToListAsync());
        }

        // GET: Avion/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Avion());
            else
                return View(_context.Aviones.Find(id));
        }

        // POST: Avion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("AvionID,Modelo,Capacidad,TipoAvion,CantMotor,Velocidad")] Avion avion)
        {
            if (ModelState.IsValid)
            {
                if (avion.AvionID == 0)
                    _context.Add(avion);
                else
                    _context.Update(avion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(avion);
        }

        // GET: Avion/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var avi = await _context.Aviones.FindAsync(id);
            _context.Aviones.Remove(avi);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

AerolineaV1/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AerolineaV1.Models;

namespace AerolineaV1.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ClienteContext _context;

        public ClienteController(ClienteContext context)
        {
            _context = context;
        }

        // GET: Cliente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Cliente/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Cliente());
            else
                return View(_context.Clientes.Find(id));
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("ClienteID,Pasaporte,Cedula,NombreCompleto,Nacionalidad,Direccion")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                if (cliente.ClienteID == 0)
                    _context.Add(cliente);
                else
                    _context.Update(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cli = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cli);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

AerolineaV1/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AerolineaV1.Models;

namespace AerolineaV1.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly EmpleadoContext _context;

        public EmpleadoController(EmpleadoContext context)
        {
            _context = context;
        }

        // GET: Empleado
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empleados.ToListAsync());
        }

        // GET: Empleado/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Empleado());
            else
                return View(_context.Empleados.Find(id));
        }

        // POST: Empleado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("EmpID,Cedula,Nombre,Puesto,Salario")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                if (empleado.EmpID == 0)
                    _context.Add(empleado);
                else
                    _context.Update(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleado/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var emp = await _context.Empleados.FindAsync(id);
            _context.Empleados.Remove(emp);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

AerolineaV1/Controllers/VueloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AerolineaV1.Models;

namespace AerolineaV1.Controllers
{
    public class VueloController : Controller
    {
        private readonly VueloContext _context;
        private EmpleadoContext _empleadoContext;

        public VueloController(VueloContext context, EmpleadoContext empleadoContext)
        {
            _context = context;
            _empleadoContext = empleadoContext;
        }

        // GET: Vuelo
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vuelos.ToListAsync());
        }

        // GET: Vuelo/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            _ = new List<Empleado>();
            List<Empleado> li = _empleadoContext.Empleados.ToList();
            ViewBag.LaPutaLista = li;

            if (id == 0)
                return View(new Vuelo());
            else
                return View(_context.Vuelos.Find(id));
        }

        // POST: Vuelo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("VueloID,Destino,Piloto,ModeloAvion,Pasajeros,FechaAbordaje,Categoria")] Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                if (vuelo.VueloID == 0)
                    _context.Add(vuelo);
                else
                    _context.Update(vuelo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vuelo);
        }


        // GET: Vuelo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var vue = await _context.Vuelos.FindAsync(id);
            _context.Vuelos.Remove(vue);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

AerolineaV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AeroApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/ca95e6a565.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AeroApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Avion" asp-action="Index">Aviones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vuelo" asp-action="Index">Vuelos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AeroApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>